---
title: "airway_GSE52778"
author: "Mikias HW"
date: "`r Sys.Date()`"
output: 
  prettydoc::html_pretty:
    theme: hpstr
    df_print: paged
---

# Load Libraries 
```{r include=FALSE}
suppressPackageStartupMessages(library("GEOquery"))
suppressPackageStartupMessages(library("airway"))
library(DESeq2)
library(iSEE)
library(iSEEde)
library("org.Hs.eg.db")
library("scater")
library("scuttle")
```

# Geo access
```{r eval=FALSE, include=FALSE}
dir <- system.file("extdata",package="airway")

geofile <- file.path(dir, "GSE52778_series_matrix.txt")

gse <- getGEO(filename=geofile)

pdata <- pData(gse)[,grepl("ch1",names(pData(gse)))]

names(pdata) <- c("treatment","tissue","ercc_mix","cell","celltype")

pdataclean <- data.frame(treatment=sub("treatment: (.*)","\\1",pdata$treatment),
                         cell=sub("cell line: (.*)","\\1",pdata$cell),
                         row.names=rownames(pdata))

pdataclean$dex <- ifelse(grepl("Dex",pdataclean$treatment),"trt","untrt")

pdataclean$albut <- ifelse(grepl("Albut",pdataclean$treatment),"trt","untrt")

pdataclean$SampleName <- rownames(pdataclean)

pdataclean$treatment <- NULL


srafile <- file.path(dir, "SraRunInfo_SRP033351.csv")

srp <- read.csv(srafile)

srpsmall <- srp[,c("Run","avgLength","Experiment","Sample","BioSample","SampleName")]


coldata <- merge(pdataclean, srpsmall, by="SampleName")

rownames(coldata) <- coldata$Run

coldata <- coldata[coldata$albut == "untrt",]

coldata$albut <- NULL

coldata

write.csv(coldata, file="sample_table.csv")

```

# RangedSummarizedExperiment
```{r include=FALSE}
data(airway)

airway

se <- airway

se

#extract counts
counts <- as.data.frame(assays(se)$counts)

#extract metadata
colData <- as.data.frame(colData(se))

#Count stats
summary(colSums(assay(se)) / 1e6)

#Introduction
metadata(se)

#Title
se@metadata[[1]]@title

#Abstract
se@metadata[[1]]@abstract

#Sample names
se@colData@rownames

#Sum of sampes
length(se@colData@rownames)

#Sum of genes
length(assays(se)$counts)

#Genome information
metadata(rowRanges(se))

dds <- DESeqDataSet(se, design = ~ cell + dex)

dds
```

# Background

## Title 
```{r echo=FALSE}
se@metadata[[1]]@title
```

## Experiment information 
```{r echo=FALSE}
metadata(se)
```

## Abstract
    `r se@metadata[[1]]@abstract`
```{r echo=FALSE}
se@metadata[[1]]@abstract
```

## Samples
```{r echo=FALSE}
se@colData@rownames
```

## Number of samples: `r length(se@colData@rownames)`
```{r echo=FALSE}
as.data.frame(colData(se))
```

## Number of Genes: `r length(assays(se)$counts)`
```{r echo=FALSE}
head(as.data.frame(assays(se)$counts))
```

## Genome Information
```{r echo=FALSE}
metadata(rowRanges(se))
```





visualize
```{r eval=FALSE, include=FALSE}
# iSEE(se)
```

# Create DESeq object
```{r}
#Ensure matching sample names & order
all(colnames(counts) %in% row.names(colData))

all(colnames(counts) == row.names(colData))

# Define design matrix for DESeq2
dds <- DESeqDataSetFromMatrix(
  countData = counts,
  colData = colData,
  design = ~ dex
)

# normalization by estimating size factor
dds <- estimateSizeFactors(dds)

# remove low expressed genes
keep <- rowSums(counts(dds)) >= 10

dds <- dds[keep, ]

# set factor level (reference group) : Im interested in comparing copd and smokers to the reference group non-smokers in this case.
dds$dex <- relevel(dds$dex, ref = "untrt")

# Run DEG analysis
dds <- DESeq(dds)

res <- results(dds)

res

resultsNames(dds)

sum(res$padj < 0.05, na.rm=TRUE)

# resLFC <- lfcShrink(dds, type="apeglm")
# 
# xlim <- c(1,1e5); ylim <- c(-3,3)
# 
# plotMA(resLFC, xlim=xlim, ylim=ylim, main="apeglm")

```


Filtering
```{r}
# keep <- rowSums(counts(dds)) >= 10
# dds <- dds[keep,]
```

Factors
```{r}
# dds$condition <- relevel(dds$condition, ref = "untreated")
```

